"""add profile_photo_url to users

Revision ID: 5b4f4ab4ff0c
Revises: 6a096ab39be4
Create Date: 2024-07-27 14:52:53.284794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4f4ab4ff0c'
down_revision = '6a096ab39be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_photo_url')

    # ### end Alembic commands ###
