"""Initial migration

Revision ID: 988c10f67a3f
Revises: 
Create Date: 2024-07-01 01:55:38.500463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988c10f67a3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.String(length=10), nullable=True),
    sa.Column('college', sa.String(length=120), nullable=True),
    sa.Column('stream', sa.String(length=120), nullable=True),
    sa.Column('move_in', sa.String(length=20), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('society', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('jugalbandi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jugalbandi',
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fullname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('age', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('college', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stream', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('move_in', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('year', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('society', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('username', name='jugalbandi_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
