"""Update user model for dating app

Revision ID: a51377721c21
Revises: e77bd299b763
Create Date: 2024-07-02 14:34:14.143036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51377721c21'
down_revision = 'e77bd299b763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('year_of_study')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_of_study', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
