"""empty message

Revision ID: e77bd299b763
Revises: 76df120774d0
Create Date: 2024-07-02 03:02:07.365743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77bd299b763'
down_revision = '76df120774d0'
branch_labels = None
depends_on = None
from sqlalchemy.sql import table, column, cast
from sqlalchemy import Integer

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_of_study', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('move_in_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('year_of_study', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('interested_in', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile_photo_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        # Modify the age column alteration
        batch_op.execute("ALTER TABLE users ALTER COLUMN age DROP DEFAULT;")
        batch_op.execute("ALTER TABLE users ALTER COLUMN age TYPE VARCHAR(50);")
        users_table = table('users', column('age'))
        op.execute(users_table.update().where(users_table.c.age != None).values(age=cast(users_table.c.age, Integer)))
        batch_op.execute("ALTER TABLE users ALTER COLUMN age TYPE INTEGER USING age::integer;")
        # Original drops
        batch_op.drop_column('society')
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('notes')
        batch_op.drop_column('move_in')
        batch_op.drop_column('stream')
        batch_op.drop_column('year')




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stream', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('move_in', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_photo', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('society', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('age',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('profile_photo_url')
        batch_op.drop_column('interested_in')
        batch_op.drop_column('interests')
        batch_op.drop_column('bio')
        batch_op.drop_column('year_of_study')
        batch_op.drop_column('move_in_date')
        batch_op.drop_column('field_of_study')

    # ### end Alembic commands ###
